#' Sample datasets with observations in ordinal and nominal data types
#'
#' @description
#'   \code{mildewScreen} is a dataset containing 222 observations of leaf
#'   phenotypes in ordinal and nominal formats from different genotypes. Technical
#'   replicate number is also recorded.
#'
#'   \code{mildewScreenOrdinal} and \code{mildewScreenCount} are supersets of
#'   \code{mildewScreen}; additional columns pasted behind \code{mildewScreen}'s
#'   data correspond to the converted ordinal and count data generated by passing
#'   \code{mildewScreen} to functions \code{\link{nominalToOrdinal}} and
#'   \code{\link{nominalToCount}} respectively.
#'
#' @docType data
#'
#' @format \code{mildewScreen} is a data.frame with 222 rows and 5 columns:
#' \describe{
#'   \item{Genotype}{genotype class}
#'   \item{replicate}{technial replicate number}
#'   \item{BGH_phenotype}{phenotype after infection with parasitic fungus, Blumeria graminis hordei (nominal, character). NA value represents normal phenotype.}
#'   \item{GO.mildew}{mildew infection severity (ordinal, character)}
#'   \item{GO_phenotype}{phenotype after infection (nominal, character). NA value represents normal phenotype.}
#'   \item{*-ordinal (In \code{mildewScreenOrdinal} columns 6-7)}{ordinal data converted from nominal data}
#'   \item{*-count (In \code{mildewScreenCount} columns 6-14)}{count data converted from nominal data}
#' }
#'
#' @keywords datasets
#'
#' @source private
"mildewScreen"
#' @rdname mildewScreen
"mildewScreenOrdinal"
#' @rdname mildewScreen
"mildewScreenCount"
